
{{ $certs := ( include "selfsignedcerts" $ ) | fromYaml }}
{{ $staticTokenData := ( include "token.metadata" $ ) }}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ . }}
{{- if and $.Values.linkTokenCreate $.Values.selfSignedCerts (eq . "skupper-link-token") }}
{{- $staticTokenData | nindent 2 }}
    edge-host: skupper-edge-{{ $.Release.Namespace }}.{{ $.Values.common.ingress.domain }}
    inter-router-host: skupper-inter-router-{{ $.Release.Namespace }}.{{ $.Values.common.ingress.domain }}
{{- end }}
data:
{{- if $.Values.selfSignedCerts }}
{{- if eq . "skupper-site-ca" }}
  tls.key: {{ $certs.cakey }}
  tls.crt: {{ $certs.cacrt }}
{{- else }}
  tls.key: {{ $certs.tlskey }}
  tls.crt: {{ $certs.tlscrt }}
  ca.crt:  {{ $certs.cacrt }}
{{- end -}}
{{- else -}}
{{ (tpl ($.Files.Glob "certs/*").AsSecrets $ ) | nindent 4 }}
{{- end -}}
{{- end }}

# Secrets for remote sites, when using custom certificates
{{ if and $.Values.linkTokenCreate (not .Values.selfSignedCerts) }}
{{ $staticTokenData := ( include "token.metadata" $ ) }}
{{- range .Values.remoteSites }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .name }}-skupper-link-token
{{- $staticTokenData | nindent 2 }}
    edge-host: {{ .edgehost }}
    inter-router-host: {{ .interrouterhost }}
data:
{{- (tpl ($.Files.Glob "certs/*").AsSecrets $ ) | nindent 2 }}
{{- end -}}
{{- end }}
