
{{ if .Values.flowCollector.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skupper-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skupper-prometheus
subjects:
- kind: ServiceAccount
  name: skupper-prometheus
{{- end }}