
{{- if and .Values.console.enabled (eq (.Values.console.auth) "internal") }}
{{ $consolesecret := ( include "consolesecret" $ ) }}
kind: Secret
apiVersion: v1
metadata:
  name: skupper-console-users
data:
{{ $consolesecret | indent 2 }}
type: Opaque
{{- end -}}
