{{ if not .Values.common.siteconfigonly }}
{{ if .Values.flowCollector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-prometheus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      skupper.io/component: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: skupper-prometheus
        app.kubernetes.io/part-of: skupper
        skupper.io/component: prometheus
    spec:
      containers:
      - args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        - --web.config.file=/etc/prometheus/web-config.yml
        image: {{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.version }}
        imagePullPolicy: Always
        name: prometheus-server
        resources:
          limits:
            cpu: {{ .Values.prometheus.cpu.limits }}
            memory: {{ .Values.prometheus.memory.limits }}
          requests:
            cpu: {{ .Values.prometheus.cpu.requests }}
            memory: {{ .Values.prometheus.memory.requests }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-config
        - mountPath: /prometheus
          name: prometheus-storage-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: skupper-prometheus
      serviceAccountName: skupper-prometheus
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-server-config
        name: prometheus-config
      - emptyDir: {}
        name: prometheus-storage-volume
{{- end }}
{{- end }}
