{{ if not .Values.siteconfigonly }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-router
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.router.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      skupper.io/component: router
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {{- include "router.annotations" . |  nindent 8 }}
      labels:
        app.kubernetes.io/name:  {{ .Values.router.name }}
        app.kubernetes.io/part-of: skupper
        application: {{ .Values.router.name }}
        skupper.io/component: router
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- include "router.labels" . |  nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ .Values.router.name }}
                  app.kubernetes.io/instance: {{ .Release.Name }}
      containers:
      - env:
        - name: APPLICATION_NAME
          value: skupper-router
        - name: SKUPPER_SITE_ID
          value: {{ include "skupper.siteuid" .}}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: QDROUTERD_AUTO_MESH_DISCOVERY
          value: QUERY
        - name: QDROUTERD_CONF
          value: /etc/skupper-router/config/skrouterd.json
        - name: QDROUTERD_CONF_TYPE
          value: json
        image: {{ .Values.router.image.repository }}:{{ .Values.router.image.version }}
        imagePullPolicy: {{ .Values.router.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
            scheme: HTTP
        name: router
        ports:
        - containerPort: 5671
          name: amqps
          protocol: TCP
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 55671
          name: inter-router
          protocol: TCP
        - containerPort: 45671
          name: edge
          protocol: TCP
        resources:
          limits:
            cpu: "{{ .Values.router.cpu.limits }}"
            memory: "{{ .Values.router.memory.limits }}"
          requests:
            cpu: "{{ .Values.router.cpu.requests }}"
            memory: "{{ .Values.router.memory.requests }}"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /etc/skupper-router/config/
            name: router-config
          - name: skupper-local-server
            mountPath: /etc/skupper-router-certs/skupper-amqps/
          - name: skupper-router-certs
            mountPath: /etc/skupper-router-certs
          - name: skupper-site-server
            mountPath: /etc/skupper-router-certs/skupper-internal/
      - image: {{ .Values.configSync.image.repository }}:{{ .Values.configSync.image.version }}
        imagePullPolicy: {{ .Values.configSync.image.pullPolicy }}
        name: config-sync
        resources:
          limits:
            cpu: "{{ .Values.configSync.cpu.limits }}"
            memory: "{{ .Values.configSync.memory.limits }}"
          requests:
            cpu: "{{ .Values.configSync.cpu.requests }}"
            memory: "{{ .Values.configSync.memory.requests }}"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/skupper-router-certs
          name: skupper-router-certs
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9191
            scheme: HTTP
      restartPolicy: Always
      serviceAccount: skupper-router
      serviceAccountName: skupper-router
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: skupper-internal
        name: router-config
      - emptyDir: {}
        name: skupper-router-certs
      - name: skupper-local-server
        secret:
          secretName: skupper-local-server
          defaultMode: 420
      - name: skupper-site-server
        secret:
          secretName: skupper-site-server
          defaultMode: 420
      - name: skupper-service-client
        secret:
          secretName: skupper-service-client
          defaultMode: 420
{{- end }}