{{ if not .Values.siteconfigonly }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels: 
{{- include "router.labels" . |  nindent 4 }}
  name: skupper-inter-router
spec:
{{- if .Values.customhostname }}
  host: {{ .Values.ingress.host }}.{{ .Values.ingress.domain }}
{{- end }}
  port:
    targetPort: inter-router
  tls:
    insecureEdgeTerminationPolicy: None
    termination: passthrough
  to:
    kind: Service
    name: skupper-router
    weight: 100
  wildcardPolicy: None
{{- end }}